# Generated by Django 5.2.10 on 2026-02-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_course_slug_alter_course_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
