# Generated by Django 5.2.10 on 2026-02-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0008_alter_profile_profile_image_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
